[tool.poetry]
name = "quinn"
version = "0.10.0"
description = "Pyspark helper methods to maximize developer efficiency"
authors = ["MrPowers <matthewkevinpowers@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/MrPowers/quinn/"
keywords = ['apachespark', 'spark', 'pyspark']

[tool.poetry.dependencies]
python = ">=3.7,<4.0"

[tool.poetry.dev-dependencies]
pyspark = ">2.0.0"
pytest = "7.4"
chispa = "0.9.2"
pytest-describe = "^2.1"
semver = "3.0.0"
ruff = "0.0.291"

[tool.poetry.group.mkdocs]
optional = true

[tool.poetry.group.mkdocs.dependencies]
mkdocstrings-python = "^0.8.3"
mkdocs-gen-files = "^0.4.0"
mkdocs-literate-nav = "^0.6.0"
mkdocs-section-index = "^0.3.5"
markdown-include = "^0.8.1"
mkdocs = "^1.4.2"

[tool.ruff]
# Allow lines to be as long as 150 characters.
line-length = 150
ignore = ["D100"]
required-version = "0.0.291"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
